# Unattended installation only supported for ISO format builds
# https://osbuild.org/docs/user-guide/blueprint-reference/#installer
[customizations.installer]
unattended = true

# Duplicated disabling of kernel mitigations already in Containerfile
[customizations.kernel]
# name - not yet supported (to assign a name)
append = "mitigations=off"

[[customizations.group]]
name = "media"
gid = 1001

[[customizations.group]]
name = "bblasco"
gid = 1000

[[customizations.user]]
name = "media"
description = "User-created for media files"
home = "/var/home/media"
#shell = "/bin/bash"
#groups = ["users", "wheel"]
uid = 1001
gid = 1001

[[customizations.user]]
name = "bblasco"
password = "$6$i9SPxDAyOKr1W21z$68B68.59AmDz1OQFhNdvctOa/F6eHKxLDNBynA57ThIw6/0Bsqrxto5rTs3fo3SHe98kO4qa8vzP8wi4Ragsu."
description = "Benjamin Blasco"
home = "/var/home/bblasco"
shell = "/bin/bash"
groups = ["wheel", "media"]
uid = 1000
gid = 1000
key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCY9P2Hh1ultuvNlBGHxQGNYlDkB35Z/kPQNR+tfsYaO2gGLhbtkVI0uoXf5SewEz5ecH+u8jHIPElXZz227h5PpxhZFzfokqUJ/U3mbEpu1/Krf4/eERCqIgz2nmXoGLlOJHgMk4MpK6LA6eb6SXZHLpxFicbEcCxUU3A9hbzhWUGDaMFG7CcExT5JAD/7VcniONxZhlJxUzyL1xmbmAN13DQpiUkew25VtuNHby1fYTgMxVaezUMfMwZn6qpNJUDXGCKX1NWv5kqB9yFxRIQbFS4zAkQPXH6w7eksNyknexRDwM1zghnaspSvE1Kn2RWIaKt5hmaoKozJuC9YnCwJ bblasco@localhost.localdomain"

# https://osbuild.org/docs/user-guide/blueprint-reference/#disk
# https://osbuild.org/docs/user-guide/partitioning/
[[customizations.disk.partitions]]
type = "lvm"
name = "fedoravg"
minsize = "20 GiB"

[[customizations.disk.partitions.logical_volumes]]
name = "rootlv"
mountpoint = "/"
label = "root"
fs_type = "xfs"
minsize = "10 GiB"

#[[customizations.disk.partitions.logical_volumes]]
#name = "homelv"
#mountpoint = "/var/home"
#label = "home"
#fs_type = "xfs"
#minsize = "5 GiB"

[[customizations.disk.partitions.logical_volumes]]
name = "varloglv"
mountpoint = "/var/log"
label = "varlog"
fs_type = "xfs"
minsize = "4 GiB"

[[customizations.disk.partitions.logical_volumes]]
name = "varlibcontainersstoragelv"
mountpoint = "/var/lib/containers/storage"
#label = "rootcontainers"
fs_type = "xfs"
minsize = "2 GiB"

[[customizations.disk.partitions.logical_volumes]]
name = "mntcontainerslv"
mountpoint = "/mnt/containers"
#label = "usercontainers"
fs_type = "xfs"
minsize = "2 GiB"

#[[customizations.disk.partitions.logical_volumes]]
#name = "varlv"
#mountpoint = "/var"
#label = "var"
#fs_type = "xfs"
#minsize = "5 GiB"

[[customizations.disk.partitions.logical_volumes]]
name = "swaplv"
fs_type = "swap"
minsize = "1 GiB"